### ISSUE TITLE
Get auto documentation on ReadTheDocs

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/deepdisc#85]
We aren't currently using this feature of the Python Project Template, we just need to turn it on, and make sure that there's a landing spot for the docs in ReadTheDocs. 

The primary ask is for auto API documentation and a tutorial/getting started page for deepdisc.

It would be good to create a few stub pages to fill in when there is time. @grantmerz if you could comment on what stub pages you would like to have to start with, that will be helpful.

**Comment by grantmerz** [comment]
Useful pages would be: Configs, Data Loading, Training, and Predictions

**Comment by OliviaLynn** [comment]
Self assigning as well as a reminder to add to the Configs section once it's on

**Comment by OliviaLynn** [comment]
Also a reminder to mention things need to be in COCO format as per #65

**Comment by dougbrn** [comment]
Readthedocs is configured and setup here: https://deepdisc.readthedocs.io/en/latest/

@grantmerz and @drewoldag have been added as maintainers, you can view the project dashboard here: https://readthedocs.org/projects/deepdisc/ 

I'll work on a quick PR to establish some stub pages for the desired pages above. My thought for these will be empty jupyter notebooks, since they will allow for easy code-blocks when needed. The other option is just plain old rst files, if any of these you don't think will have any included code, or just prefer rst. Let me know and I can make sure they're established accordingly.
